// Realistic seed dataset for JobGraph. Kept as plain data (no Cypher here) so
// it can be inspected/edited without touching the write logic in seed.ts.

export interface SeedSkill {
  id: string;
  name: string;
  category: string;
}

export interface SeedTechnology {
  id: string;
  name: string;
  category: string;
}

export interface SeedCompany {
  id: string;
  name: string;
  industry: string;
  location: string;
}

export interface SeedProject {
  id: string;
  name: string;
  description: string;
  duration: string;
  domain: string;
  technologyIds: string[];
}

export interface SeedJob {
  id: string;
  title: string;
  description: string;
  location: string;
  experienceRequired: number;
  employmentType: string;
  companyId: string;
  skillIds: string[];
  technologyIds: string[];
}

export interface SeedCandidate {
  id: string;
  name: string;
  email: string;
  yearsExperience: number;
  location: string;
  role: string;
  skillIds: string[];
  technologyIds: string[];
  projects: { projectId: string; role: string }[];
}

export const skills: SeedSkill[] = [
  { id: "skill-java", name: "Java", category: "Language" },
  { id: "skill-javascript", name: "JavaScript", category: "Language" },
  { id: "skill-typescript", name: "TypeScript", category: "Language" },
  { id: "skill-python", name: "Python", category: "Language" },
  { id: "skill-go", name: "Go", category: "Language" },
  { id: "skill-sql", name: "SQL", category: "Database" },
  { id: "skill-aws", name: "AWS", category: "Cloud" },
  { id: "skill-system-design", name: "System Design", category: "Engineering Practice" },
  { id: "skill-dsa", name: "Data Structures & Algorithms", category: "Engineering Practice" },
  { id: "skill-agile", name: "Agile/Scrum", category: "Engineering Practice" },
  { id: "skill-communication", name: "Communication", category: "Soft Skill" },
  { id: "skill-problem-solving", name: "Problem Solving", category: "Soft Skill" },
];

export const technologies: SeedTechnology[] = [
  { id: "tech-spring-boot", name: "Spring Boot", category: "Backend Framework" },
  { id: "tech-react", name: "React", category: "Frontend Framework" },
  { id: "tech-nodejs", name: "Node.js", category: "Runtime" },
  { id: "tech-express", name: "Express", category: "Backend Framework" },
  { id: "tech-kafka", name: "Kafka", category: "Messaging" },
  { id: "tech-postgresql", name: "PostgreSQL", category: "Database" },
  { id: "tech-mongodb", name: "MongoDB", category: "Database" },
  { id: "tech-redis", name: "Redis", category: "Cache" },
  { id: "tech-graphql", name: "GraphQL", category: "API" },
  { id: "tech-nextjs", name: "Next.js", category: "Frontend Framework" },
  { id: "tech-django", name: "Django", category: "Backend Framework" },
  { id: "tech-flask", name: "Flask", category: "Backend Framework" },
  { id: "tech-tensorflow", name: "TensorFlow", category: "Machine Learning" },
  { id: "tech-docker", name: "Docker", category: "DevOps" },
  { id: "tech-kubernetes", name: "Kubernetes", category: "DevOps" },
  { id: "tech-terraform", name: "Terraform", category: "Infrastructure" },
  { id: "tech-vuejs", name: "Vue.js", category: "Frontend Framework" },
  { id: "tech-elasticsearch", name: "Elasticsearch", category: "Search" },
];

export const companies: SeedCompany[] = [
  { id: "company-techcorp", name: "TechCorp Solutions", industry: "Enterprise Software", location: "Austin, TX" },
  { id: "company-nimbus", name: "Nimbus Cloud Systems", industry: "Cloud Infrastructure", location: "Seattle, WA" },
  { id: "company-fintechwave", name: "Fintech Wave", industry: "Financial Technology", location: "New York, NY" },
  { id: "company-healthbridge", name: "HealthBridge Analytics", industry: "Healthcare Technology", location: "Boston, MA" },
  { id: "company-retailloop", name: "RetailLoop", industry: "E-commerce", location: "Chicago, IL" },
  { id: "company-dataforge", name: "DataForge Labs", industry: "Data & Analytics", location: "San Francisco, CA" },
  { id: "company-streamline", name: "StreamLine Media", industry: "Streaming & Media", location: "Los Angeles, CA" },
  { id: "company-greengrid", name: "GreenGrid Energy", industry: "Clean Energy Technology", location: "Denver, CO" },
  { id: "company-quantum", name: "Quantum Logistics", industry: "Supply Chain Technology", location: "Atlanta, GA" },
  { id: "company-pixelpattern", name: "Pixel & Pattern Studio", industry: "Consumer Software", location: "Portland, OR" },
  { id: "company-securestack", name: "SecureStack", industry: "Cybersecurity", location: "Remote" },
  { id: "company-edusphere", name: "EduSphere", industry: "Education Technology", location: "Remote" },
];

export const projects: SeedProject[] = [
  {
    id: "proj-1",
    name: "E-commerce Order Platform",
    description: "Rebuilt the order and checkout service to handle Black Friday-scale traffic with async event processing.",
    duration: "8 months",
    domain: "E-commerce",
    technologyIds: ["tech-spring-boot", "tech-postgresql", "tech-docker", "tech-kafka"],
  },
  {
    id: "proj-2",
    name: "Multi-Region Deployment Pipeline",
    description: "Designed a blue/green deployment pipeline across three cloud regions with automated rollback.",
    duration: "1 year",
    domain: "Cloud Infrastructure",
    technologyIds: ["tech-kubernetes", "tech-terraform", "tech-docker", "tech-elasticsearch"],
  },
  {
    id: "proj-3",
    name: "Personal Finance Dashboard",
    description: "Built a budgeting dashboard that aggregates bank transactions and visualizes spending trends.",
    duration: "5 months",
    domain: "Financial Technology",
    technologyIds: ["tech-react", "tech-nodejs", "tech-express", "tech-postgresql", "tech-graphql"],
  },
  {
    id: "proj-4",
    name: "Patient Records Integration Service",
    description: "Led integration of three hospital EHR systems into a unified, HIPAA-compliant records API.",
    duration: "1.5 years",
    domain: "Healthcare",
    technologyIds: ["tech-spring-boot", "tech-kafka", "tech-postgresql", "tech-docker"],
  },
  {
    id: "proj-5",
    name: "Claims Processing Engine",
    description: "Built a rules-based engine to auto-adjudicate routine insurance claims, cutting manual review time.",
    duration: "10 months",
    domain: "Healthcare / Insurance",
    technologyIds: ["tech-spring-boot", "tech-postgresql", "tech-redis"],
  },
  {
    id: "proj-6",
    name: "Storefront Redesign",
    description: "Rebuilt the customer-facing storefront as a server-rendered app to improve load time and SEO.",
    duration: "6 months",
    domain: "E-commerce",
    technologyIds: ["tech-react", "tech-nextjs", "tech-graphql"],
  },
  {
    id: "proj-7",
    name: "Realtime Analytics Pipeline",
    description: "Built a streaming pipeline that indexes clickstream events for near-real-time dashboards.",
    duration: "9 months",
    domain: "Data & Analytics",
    technologyIds: ["tech-kafka", "tech-postgresql", "tech-elasticsearch", "tech-docker"],
  },
  {
    id: "proj-8",
    name: "Content Recommendation Engine",
    description: "Built a collaborative-filtering recommendation service powering the homepage content rail.",
    duration: "1 year",
    domain: "Streaming & Media",
    technologyIds: ["tech-tensorflow", "tech-flask", "tech-postgresql", "tech-docker"],
  },
  {
    id: "proj-9",
    name: "Viewer Churn Prediction Model",
    description: "Trained and deployed a churn-prediction model consuming near-real-time viewing behavior events.",
    duration: "6 months",
    domain: "Streaming & Media",
    technologyIds: ["tech-tensorflow", "tech-kafka", "tech-postgresql"],
  },
  {
    id: "proj-10",
    name: "Smart Grid Telemetry Service",
    description: "Built an ingestion service for smart-meter telemetry supporting millions of daily readings.",
    duration: "8 months",
    domain: "Clean Energy",
    technologyIds: ["tech-docker", "tech-postgresql", "tech-redis"],
  },
  {
    id: "proj-11",
    name: "Fleet Tracking Dashboard",
    description: "Built a live dashboard for tracking delivery fleet location, ETA, and load status.",
    duration: "7 months",
    domain: "Supply Chain & Logistics",
    technologyIds: ["tech-vuejs", "tech-nodejs", "tech-express", "tech-mongodb"],
  },
  {
    id: "proj-12",
    name: "Zero Trust Access Gateway",
    description: "Designed a zero-trust access gateway replacing VPN-based access for internal services.",
    duration: "1 year",
    domain: "Cybersecurity",
    technologyIds: ["tech-docker", "tech-kubernetes", "tech-terraform", "tech-postgresql"],
  },
  {
    id: "proj-13",
    name: "Inventory Sync Service",
    description: "Built a service that reconciles inventory counts across warehouses and the storefront in near real time.",
    duration: "4 months",
    domain: "E-commerce",
    technologyIds: ["tech-spring-boot", "tech-redis", "tech-docker"],
  },
  {
    id: "proj-14",
    name: "Recipe Sharing Social App",
    description: "Built a social app for sharing and rating recipes, including a feed and comments system.",
    duration: "3 months",
    domain: "Consumer Social",
    technologyIds: ["tech-react", "tech-nodejs", "tech-mongodb"],
  },
  {
    id: "proj-15",
    name: "Design System Component Library",
    description: "Built a shared component library adopted across three product teams' frontends.",
    duration: "4 months",
    domain: "Design Systems",
    technologyIds: ["tech-react", "tech-vuejs", "tech-nextjs"],
  },
  {
    id: "proj-16",
    name: "Warehouse Inventory Portal",
    description: "Built an internal portal for warehouse staff to manage stock levels and transfer requests.",
    duration: "5 months",
    domain: "Supply Chain & Logistics",
    technologyIds: ["tech-vuejs", "tech-nodejs", "tech-graphql"],
  },
];

export const jobs: SeedJob[] = [
  {
    id: "job-1",
    title: "Backend Engineer",
    description: "Own core order and payments services on our Java/Spring Boot backend.",
    location: "Austin, TX",
    experienceRequired: 3,
    employmentType: "Full-time",
    companyId: "company-techcorp",
    skillIds: ["skill-java", "skill-sql", "skill-system-design"],
    technologyIds: ["tech-spring-boot", "tech-postgresql", "tech-docker"],
  },
  {
    id: "job-2",
    title: "Senior Java Developer",
    description: "Lead design of high-throughput services for our enterprise billing platform.",
    location: "Austin, TX",
    experienceRequired: 6,
    employmentType: "Full-time",
    companyId: "company-techcorp",
    skillIds: ["skill-java", "skill-sql", "skill-system-design", "skill-dsa"],
    technologyIds: ["tech-spring-boot", "tech-kafka", "tech-postgresql", "tech-docker"],
  },
  {
    id: "job-3",
    title: "DevOps Engineer",
    description: "Build and operate CI/CD pipelines and cloud infrastructure for enterprise customers.",
    location: "Austin, TX",
    experienceRequired: 4,
    employmentType: "Full-time",
    companyId: "company-techcorp",
    skillIds: ["skill-aws", "skill-system-design"],
    technologyIds: ["tech-docker", "tech-kubernetes", "tech-terraform"],
  },
  {
    id: "job-4",
    title: "Cloud Platform Engineer",
    description: "Design and operate the multi-tenant Kubernetes platform our customers deploy onto.",
    location: "Seattle, WA",
    experienceRequired: 5,
    employmentType: "Full-time",
    companyId: "company-nimbus",
    skillIds: ["skill-aws", "skill-system-design", "skill-communication"],
    technologyIds: ["tech-kubernetes", "tech-terraform", "tech-docker"],
  },
  {
    id: "job-5",
    title: "Site Reliability Engineer",
    description: "Own uptime and incident response for our globally distributed cloud platform.",
    location: "Remote",
    experienceRequired: 4,
    employmentType: "Full-time",
    companyId: "company-nimbus",
    skillIds: ["skill-aws", "skill-problem-solving", "skill-system-design"],
    technologyIds: ["tech-kubernetes", "tech-docker", "tech-elasticsearch"],
  },
  {
    id: "job-6",
    title: "Infrastructure Engineer",
    description: "Automate provisioning of customer environments using infrastructure-as-code.",
    location: "Seattle, WA",
    experienceRequired: 3,
    employmentType: "Full-time",
    companyId: "company-nimbus",
    skillIds: ["skill-aws", "skill-sql"],
    technologyIds: ["tech-terraform", "tech-docker", "tech-postgresql"],
  },
  {
    id: "job-7",
    title: "Full Stack Developer",
    description: "Build customer-facing budgeting tools end to end, from API to UI.",
    location: "New York, NY",
    experienceRequired: 2,
    employmentType: "Full-time",
    companyId: "company-fintechwave",
    skillIds: ["skill-javascript", "skill-typescript", "skill-sql"],
    technologyIds: ["tech-react", "tech-nodejs", "tech-postgresql"],
  },
  {
    id: "job-8",
    title: "Backend Engineer, Payments",
    description: "Build reliable, auditable payment processing services on the JVM.",
    location: "New York, NY",
    experienceRequired: 4,
    employmentType: "Full-time",
    companyId: "company-fintechwave",
    skillIds: ["skill-java", "skill-sql", "skill-system-design"],
    technologyIds: ["tech-spring-boot", "tech-kafka", "tech-postgresql"],
  },
  {
    id: "job-9",
    title: "Frontend Engineer",
    description: "Build fast, accessible React interfaces for our trading dashboard.",
    location: "Remote",
    experienceRequired: 2,
    employmentType: "Full-time",
    companyId: "company-fintechwave",
    skillIds: ["skill-javascript", "skill-typescript", "skill-communication"],
    technologyIds: ["tech-react", "tech-graphql", "tech-nextjs"],
  },
  {
    id: "job-10",
    title: "Senior Backend Engineer",
    description: "Design the next generation of our clinical data integration platform.",
    location: "Boston, MA",
    experienceRequired: 7,
    employmentType: "Full-time",
    companyId: "company-healthbridge",
    skillIds: ["skill-java", "skill-system-design", "skill-dsa"],
    technologyIds: ["tech-spring-boot", "tech-kafka", "tech-postgresql", "tech-docker"],
  },
  {
    id: "job-11",
    title: "Data Engineer",
    description: "Build ETL pipelines that power population-health analytics for care teams.",
    location: "Boston, MA",
    experienceRequired: 4,
    employmentType: "Full-time",
    companyId: "company-healthbridge",
    skillIds: ["skill-python", "skill-sql", "skill-problem-solving"],
    technologyIds: ["tech-kafka", "tech-postgresql", "tech-elasticsearch"],
  },
  {
    id: "job-12",
    title: "Full Stack Developer",
    description: "Ship features across our patient engagement portal, a Node/React application.",
    location: "Remote",
    experienceRequired: 3,
    employmentType: "Contract",
    companyId: "company-healthbridge",
    skillIds: ["skill-javascript", "skill-typescript", "skill-sql"],
    technologyIds: ["tech-react", "tech-nodejs", "tech-mongodb"],
  },
  {
    id: "job-13",
    title: "Backend Engineer",
    description: "Build the services behind checkout, promotions, and order fulfillment.",
    location: "Chicago, IL",
    experienceRequired: 3,
    employmentType: "Full-time",
    companyId: "company-retailloop",
    skillIds: ["skill-java", "skill-sql", "skill-agile"],
    technologyIds: ["tech-spring-boot", "tech-postgresql", "tech-docker", "tech-kafka"],
  },
  {
    id: "job-14",
    title: "Frontend Developer",
    description: "Build and optimize the shopping experience across web and mobile web.",
    location: "Chicago, IL",
    experienceRequired: 2,
    employmentType: "Full-time",
    companyId: "company-retailloop",
    skillIds: ["skill-javascript", "skill-typescript", "skill-communication"],
    technologyIds: ["tech-react", "tech-nextjs", "tech-graphql"],
  },
  {
    id: "job-15",
    title: "Site Reliability Engineer",
    description: "Keep the storefront online during peak shopping events at massive scale.",
    location: "Remote",
    experienceRequired: 5,
    employmentType: "Full-time",
    companyId: "company-retailloop",
    skillIds: ["skill-aws", "skill-system-design"],
    technologyIds: ["tech-kubernetes", "tech-docker", "tech-redis"],
  },
  {
    id: "job-16",
    title: "Data Engineer",
    description: "Build pipelines feeding our customer analytics warehouse.",
    location: "San Francisco, CA",
    experienceRequired: 4,
    employmentType: "Full-time",
    companyId: "company-dataforge",
    skillIds: ["skill-python", "skill-sql", "skill-dsa"],
    technologyIds: ["tech-kafka", "tech-postgresql", "tech-elasticsearch", "tech-docker"],
  },
  {
    id: "job-17",
    title: "Machine Learning Engineer",
    description: "Build and productionize models that power client-facing analytics products.",
    location: "San Francisco, CA",
    experienceRequired: 5,
    employmentType: "Full-time",
    companyId: "company-dataforge",
    skillIds: ["skill-python", "skill-dsa", "skill-system-design"],
    technologyIds: ["tech-tensorflow", "tech-flask", "tech-docker"],
  },
  {
    id: "job-18",
    title: "Analytics Platform Engineer",
    description: "Operate the query and indexing layer behind our self-serve analytics product.",
    location: "Remote",
    experienceRequired: 3,
    employmentType: "Full-time",
    companyId: "company-dataforge",
    skillIds: ["skill-python", "skill-sql"],
    technologyIds: ["tech-postgresql", "tech-elasticsearch", "tech-redis"],
  },
  {
    id: "job-19",
    title: "Machine Learning Engineer",
    description: "Improve the models that power personalized content recommendations for viewers.",
    location: "Los Angeles, CA",
    experienceRequired: 4,
    employmentType: "Full-time",
    companyId: "company-streamline",
    skillIds: ["skill-python", "skill-dsa", "skill-communication"],
    technologyIds: ["tech-tensorflow", "tech-kafka", "tech-postgresql"],
  },
  {
    id: "job-20",
    title: "Backend Engineer",
    description: "Build services powering content metadata and playback for our streaming app.",
    location: "Los Angeles, CA",
    experienceRequired: 3,
    employmentType: "Full-time",
    companyId: "company-streamline",
    skillIds: ["skill-python", "skill-sql", "skill-system-design"],
    technologyIds: ["tech-flask", "tech-postgresql", "tech-docker"],
  },
  {
    id: "job-21",
    title: "Data Scientist",
    description: "Model viewer engagement and churn to inform content investment decisions.",
    location: "Remote",
    experienceRequired: 5,
    employmentType: "Full-time",
    companyId: "company-streamline",
    skillIds: ["skill-python", "skill-dsa", "skill-problem-solving"],
    technologyIds: ["tech-tensorflow", "tech-postgresql"],
  },
  {
    id: "job-22",
    title: "Backend Engineer",
    description: "Build services that process smart-meter telemetry at grid scale.",
    location: "Denver, CO",
    experienceRequired: 3,
    employmentType: "Full-time",
    companyId: "company-greengrid",
    skillIds: ["skill-go", "skill-sql", "skill-system-design"],
    technologyIds: ["tech-docker", "tech-postgresql", "tech-redis"],
  },
  {
    id: "job-23",
    title: "Cloud Platform Engineer",
    description: "Operate the cloud platform underpinning our grid monitoring products.",
    location: "Denver, CO",
    experienceRequired: 5,
    employmentType: "Full-time",
    companyId: "company-greengrid",
    skillIds: ["skill-aws", "skill-system-design", "skill-problem-solving"],
    technologyIds: ["tech-kubernetes", "tech-docker", "tech-terraform"],
  },
  {
    id: "job-24",
    title: "IoT Systems Engineer",
    description: "Build ingestion services for high-volume sensor data from field devices.",
    location: "Denver, CO",
    experienceRequired: 4,
    employmentType: "Full-time",
    companyId: "company-greengrid",
    skillIds: ["skill-go", "skill-problem-solving"],
    technologyIds: ["tech-docker", "tech-postgresql", "tech-kafka"],
  },
  {
    id: "job-25",
    title: "Full Stack Developer",
    description: "Build features across our fleet management web application.",
    location: "Atlanta, GA",
    experienceRequired: 3,
    employmentType: "Full-time",
    companyId: "company-quantum",
    skillIds: ["skill-javascript", "skill-typescript", "skill-sql", "skill-agile"],
    technologyIds: ["tech-vuejs", "tech-nodejs", "tech-mongodb"],
  },
  {
    id: "job-26",
    title: "Backend Engineer",
    description: "Build APIs powering shipment tracking and warehouse coordination.",
    location: "Atlanta, GA",
    experienceRequired: 2,
    employmentType: "Full-time",
    companyId: "company-quantum",
    skillIds: ["skill-javascript", "skill-sql"],
    technologyIds: ["tech-nodejs", "tech-express", "tech-mongodb"],
  },
  {
    id: "job-27",
    title: "Full Stack Developer",
    description: "Build internal tools used by warehouse and logistics teams daily.",
    location: "Remote",
    experienceRequired: 4,
    employmentType: "Full-time",
    companyId: "company-quantum",
    skillIds: ["skill-javascript", "skill-typescript", "skill-agile"],
    technologyIds: ["tech-vuejs", "tech-nodejs", "tech-graphql"],
  },
  {
    id: "job-28",
    title: "Frontend Developer",
    description: "Craft polished, accessible interfaces for our design tools product.",
    location: "Portland, OR",
    experienceRequired: 2,
    employmentType: "Full-time",
    companyId: "company-pixelpattern",
    skillIds: ["skill-javascript", "skill-typescript", "skill-communication"],
    technologyIds: ["tech-react", "tech-nextjs"],
  },
  {
    id: "job-29",
    title: "Frontend Engineer",
    description: "Maintain our shared component library and consumer-facing marketing sites.",
    location: "Remote",
    experienceRequired: 3,
    employmentType: "Contract",
    companyId: "company-pixelpattern",
    skillIds: ["skill-javascript", "skill-typescript"],
    technologyIds: ["tech-react", "tech-vuejs", "tech-graphql"],
  },
  {
    id: "job-30",
    title: "Security Engineer",
    description: "Design access-control systems and lead security reviews across the platform.",
    location: "Remote",
    experienceRequired: 6,
    employmentType: "Full-time",
    companyId: "company-securestack",
    skillIds: ["skill-python", "skill-system-design", "skill-communication", "skill-problem-solving"],
    technologyIds: ["tech-docker", "tech-kubernetes", "tech-terraform"],
  },
  {
    id: "job-31",
    title: "Backend Engineer, Platform",
    description: "Build the core services behind our identity and access management product.",
    location: "Remote",
    experienceRequired: 4,
    employmentType: "Full-time",
    companyId: "company-securestack",
    skillIds: ["skill-go", "skill-sql", "skill-system-design"],
    technologyIds: ["tech-docker", "tech-kubernetes", "tech-postgresql"],
  },
  {
    id: "job-32",
    title: "Site Reliability Engineer",
    description: "Own the reliability and security posture of our production Kubernetes clusters.",
    location: "Remote",
    experienceRequired: 5,
    employmentType: "Full-time",
    companyId: "company-securestack",
    skillIds: ["skill-aws", "skill-problem-solving"],
    technologyIds: ["tech-kubernetes", "tech-terraform", "tech-docker"],
  },
  {
    id: "job-33",
    title: "Full Stack Developer",
    description: "Build features for our student-facing learning platform used by thousands of classrooms.",
    location: "Remote",
    experienceRequired: 2,
    employmentType: "Full-time",
    companyId: "company-edusphere",
    skillIds: ["skill-javascript", "skill-typescript", "skill-sql"],
    technologyIds: ["tech-react", "tech-nodejs", "tech-postgresql"],
  },
  {
    id: "job-34",
    title: "Backend Engineer",
    description: "Build the course-authoring and grading services behind our platform.",
    location: "Remote",
    experienceRequired: 3,
    employmentType: "Full-time",
    companyId: "company-edusphere",
    skillIds: ["skill-python", "skill-sql", "skill-agile"],
    technologyIds: ["tech-django", "tech-postgresql", "tech-docker"],
  },
  {
    id: "job-35",
    title: "Data Engineer",
    description: "Build the analytics pipeline that helps teachers understand student progress.",
    location: "Remote",
    experienceRequired: 4,
    employmentType: "Full-time",
    companyId: "company-edusphere",
    skillIds: ["skill-python", "skill-sql", "skill-dsa"],
    technologyIds: ["tech-postgresql", "tech-elasticsearch", "tech-kafka"],
  },
];

export const candidates: SeedCandidate[] = [
  {
    id: "cand-1",
    name: "Maria Chen",
    email: "maria.chen@example.com",
    yearsExperience: 4,
    location: "Austin, TX",
    role: "Backend Engineer",
    skillIds: ["skill-java", "skill-sql", "skill-system-design", "skill-problem-solving", "skill-agile"],
    technologyIds: ["tech-spring-boot", "tech-postgresql", "tech-docker"],
    projects: [
      { projectId: "proj-1", role: "Backend Engineer" },
      { projectId: "proj-13", role: "Backend Engineer" },
    ],
  },
  {
    id: "cand-2",
    name: "David Okafor",
    email: "david.okafor@example.com",
    yearsExperience: 6,
    location: "Seattle, WA",
    role: "Cloud Platform Engineer",
    skillIds: ["skill-aws", "skill-python", "skill-system-design", "skill-communication"],
    technologyIds: ["tech-kubernetes", "tech-terraform", "tech-docker"],
    projects: [{ projectId: "proj-2", role: "DevOps Lead" }],
  },
  {
    id: "cand-3",
    name: "Priya Sharma",
    email: "priya.sharma@example.com",
    yearsExperience: 3,
    location: "New York, NY",
    role: "Full Stack Developer",
    skillIds: ["skill-javascript", "skill-typescript", "skill-sql", "skill-problem-solving"],
    technologyIds: ["tech-react", "tech-nodejs", "tech-express", "tech-postgresql"],
    projects: [
      { projectId: "proj-3", role: "Full Stack Developer" },
      { projectId: "proj-14", role: "Full Stack Developer" },
    ],
  },
  {
    id: "cand-4",
    name: "James Whitfield",
    email: "james.whitfield@example.com",
    yearsExperience: 8,
    location: "Boston, MA",
    role: "Senior Java Developer",
    skillIds: ["skill-java", "skill-sql", "skill-system-design", "skill-dsa", "skill-agile"],
    technologyIds: ["tech-spring-boot", "tech-kafka", "tech-postgresql", "tech-docker"],
    projects: [
      { projectId: "proj-4", role: "Tech Lead" },
      { projectId: "proj-5", role: "Senior Engineer" },
    ],
  },
  {
    id: "cand-5",
    name: "Sofia Marin",
    email: "sofia.marin@example.com",
    yearsExperience: 2,
    location: "Chicago, IL",
    role: "Frontend Developer",
    skillIds: ["skill-javascript", "skill-typescript", "skill-communication"],
    technologyIds: ["tech-react", "tech-nextjs", "tech-graphql"],
    projects: [
      { projectId: "proj-6", role: "Frontend Developer" },
      { projectId: "proj-15", role: "Frontend Developer" },
    ],
  },
  {
    id: "cand-6",
    name: "Ethan Brooks",
    email: "ethan.brooks@example.com",
    yearsExperience: 5,
    location: "San Francisco, CA",
    role: "Data Engineer",
    skillIds: ["skill-python", "skill-sql", "skill-dsa", "skill-problem-solving"],
    technologyIds: ["tech-kafka", "tech-postgresql", "tech-elasticsearch", "tech-docker"],
    projects: [{ projectId: "proj-7", role: "Data Engineer" }],
  },
  {
    id: "cand-7",
    name: "Grace Lin",
    email: "grace.lin@example.com",
    yearsExperience: 7,
    location: "Los Angeles, CA",
    role: "Machine Learning Engineer",
    skillIds: ["skill-python", "skill-dsa", "skill-system-design", "skill-communication"],
    technologyIds: ["tech-tensorflow", "tech-flask", "tech-docker", "tech-postgresql"],
    projects: [
      { projectId: "proj-8", role: "ML Engineer" },
      { projectId: "proj-9", role: "ML Engineer" },
    ],
  },
  {
    id: "cand-8",
    name: "Noah Kimathi",
    email: "noah.kimathi@example.com",
    yearsExperience: 4,
    location: "Denver, CO",
    role: "Backend Engineer",
    skillIds: ["skill-go", "skill-sql", "skill-system-design", "skill-problem-solving"],
    technologyIds: ["tech-docker", "tech-kubernetes", "tech-postgresql", "tech-redis"],
    projects: [{ projectId: "proj-10", role: "Backend Engineer" }],
  },
  {
    id: "cand-9",
    name: "Isabella Rossi",
    email: "isabella.rossi@example.com",
    yearsExperience: 3,
    location: "Atlanta, GA",
    role: "Full Stack Developer",
    skillIds: ["skill-javascript", "skill-typescript", "skill-sql", "skill-agile"],
    technologyIds: ["tech-vuejs", "tech-nodejs", "tech-express", "tech-mongodb"],
    projects: [
      { projectId: "proj-11", role: "Full Stack Developer" },
      { projectId: "proj-16", role: "Full Stack Developer" },
    ],
  },
  {
    id: "cand-10",
    name: "Liam Johansson",
    email: "liam.johansson@example.com",
    yearsExperience: 9,
    location: "Remote",
    role: "Security Engineer",
    skillIds: ["skill-python", "skill-system-design", "skill-communication", "skill-problem-solving", "skill-dsa"],
    technologyIds: ["tech-docker", "tech-kubernetes", "tech-terraform", "tech-postgresql"],
    projects: [{ projectId: "proj-12", role: "Security Architect" }],
  },
];
